name: Update Offsets from Decompiled Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'


concurrency:
  group: offsets-${{ github.ref }}
  cancel-in-progress: true


jobs:
  update-offsets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Upstream Decomps Repo
        run: |
		  git ls-remote https://github.com/calamity-inc/GTA-V-Decompiled-Scripts HEAD | cut -f1 > upstream_commit.txt

      - name: Read Last Commit Hash
        id: last
        run: |
          if [ -f scripts/offsets/.last_commit_hash ]; then
            cat scripts/.last_commit_hash > last_commit.txt
          else
            echo "none" > last_commit.txt
          fi

      - name: Compare Commit
        id: compare_commit
        run: |
          UPSTREAM=$(cat upstream_commit.txt)
          LAST=$(cat last_commit.txt)

          echo "Upstream: $UPSTREAM"
          echo "Last run: $LAST"

          if [ "$UPSTREAM" = "$LAST" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "run=false" >> $GITHUB_OUTPUT
          else
            echo "run=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        if: steps.compare_commit.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"

      - name: Run Offset Updater
        if: steps.compare_commit.outputs.run == 'true'
        run: |
          python scripts/offsets/update_offsets.py

      - name: Save New Commit Hash
        if: steps.compare_commit.outputs.run == 'true'
        run: |
          cp upstream_commit.txt scripts/offsets/.last_commit_hash

      - name: Commit Changes
        if: steps.compare_commit.outputs.run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/offsets/.last_commit_hash
          git add includes/data/globals_locals.lua
          git diff --cached --quiet || git commit -m "chore(offsets): update script globals & locals from upstream"
          git push
