name: Generate Translations

on:
  push:
    paths:
      - "scripts/translations/**"
      - "SSV2/includes/lib/translations/en-US.lua"
      - "SSV2/includes/lib/translations/__locales.lua"
  workflow_dispatch:

concurrency:
  group: ss_translations-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.x"

    - name: Run Generator
      run: |
        cd ./scripts/translations
        python generate_translations.py

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add SSV2/includes/lib/translations/
        git diff --cached --quiet || git commit -m "feat(Translations): update translations"
        git push
