name: Generate Translations

on:
  push:
    paths:
      - "scripts/translations/**"
      - "includes/lib/translations/en-US.lua"
      - "includes/lib/translations/__locales.lua"
  workflow_dispatch:

concurrency:
  group: ss_ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generator:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4
       
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.x"

    - name: Run Translations Generator
      run: |
        cd ./scripts/translations
        python generate_translations.py

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add includes/lib/translations/
        git add scripts/translations/hashmap.json || true
        git diff --cached --quiet || git commit -m "feat(Translations): update translations"
        git push
